# Generated by Django 6.1 on 2026-08-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Archived'), (3, 'Deleted')]),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_status',
            field=models.IntegerField(choices=[(1, 'Ongoing'), (2, 'Planned'), (3, 'Completed'), (4, 'Failed')]),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_type',
            field=models.IntegerField(choices=[(1, 'Internal'), (2, 'External')]),
        ),
    ]
